
export const register = {
    REGISTER_REQUEST : "REGISTER_REQUEST",
    REGISTER_SUCCESS : "REGISTER_SUCCESS",
    REGISTER_FAILURE : "REGISTER_FAILURE"
};

export const login = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE"
};

export const LOGOUT = "LOGOUT";

export const airplanes = {
    GETALL_SUCCESS : "GETALL_SUCCESS",
    GETALL_FAILURE : "GETALL_FAILURE",

    GETONE_SUCCESS : "GETONE_SUCCESS",
    GETONE_FAILURE : "GETONE_FAILURE",


}
